### ISSUE TITLE
 Unable to locate package zevenet

### ISSUE THREAD

**Issue by joeyboli** [zevenet/zlb#101]
Not Installing

**Comment by cano-devel** [comment]
Hello, 
could you give us more details?

Did you follow the installation steps?
https://github.com/zevenet/zlb#installation-on-debian-buster

Kind regards

**Comment by joeyboli** [comment]
yes I did. I use debian 10 Buster.

**Comment by cano-devel** [comment]
Hello @adoboligh1 

Sorry so much for the delay but I just realized that the ZEVENET package repository is missing in the installation guide, you should add the following line in the Debian repositories directory "/etc/apt/source.list.d/zevenet.list"

```
deb http://repo.zevenet.com/ce/v5 buster main
```

If you want to deploy a Zevenet load balancer in an easier way, you can use the ZEVENET ISO, It is available in the following link, clicking on the "download ISO image" button:

https://www.zevenet.com/products/community/

best regards
