### ISSUE TITLE
Farm type graphs do not work for farms of type HTTP.

### ISSUE THREAD

**Issue by jurgenschepers** [zevenet/zlb#11]
The graphs are generated from conntrack but HTTP farms run via Pound. So the results are always 0.

**Comment by nevola** [comment]
Hi Jurgen, please include the module "ip_conntrack" into /etc/modules-load.d/modules.conf
in order to be loaded at boot time, but also execute "modprobe ip_conntrack" in order to avoid the reboot.

Please confirm that is working for you,
Regards.

**Comment by jurgenschepers** [comment]
That seems to work, but shouldn't Zevenet do this instead of me manually?

**Comment by nevola** [comment]
Yes, it'll do that at boot time.
https://github.com/zevenet/zlb/commit/f3a668a83887bc4864944a7192c40ea123a3ea0f

Regards!
