### ISSUE TITLE
Install 5.12 Debian Buster

### ISSUE THREAD

**Issue by dboc** [zevenet/zlb#116]
Hi,

I tried to install the zevenet version 5.12 on a Debian Buster, but there is an error when install it through apt packages. I did the follow steps:

```bash
apt update && upgrade -y
apt install gnupg
echo "deb http://repo.zevenet.com/ce/v5 buster main" >> /etc/apt/sources.list.d/zevenet.list
wget -O - http://repo.zevenet.com/zevenet.com.gpg.key | apt-key add -
apt update && upgrade -y
```
Then, install zevenet
`apt install zevenet`
Outuput:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 zevenet : Depends: libnftables1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

is there  something wrong?

**Comment by adanmarin-zevenet** [comment]
Hello, thanks for the report.

There is a bug in the package dependencies, the issue will be fixed in the next release. Will keep you posted.

Sorry for the inconvenience.

Kind regards.

**Comment by dboc** [comment]
@adanmarin-zevenet Thank you.

Additionaly, The End Of Life of Debian Buster is 08-2022, is there any plan to use the Debian Bullseye?

Another information about the error, libnftables1 is marked as oldstable in Debian Buster main packages, but it list in buster-backports package. If you add the repository buster-backports, zevenet will installed but appear another dependencies error when try to install zcli.

I hope this help you, i will wait the next release.

**Comment by adanmarin-zevenet** [comment]
Good day dboc.

We have released a hotfix where the experienced issue should be fixed and we have also updated the documentation with the new procedure.

Please follow the procedure below for a fast configuration for ZEVENET
Community Edition APT repository:

# wget -O - http://repo.zevenet.com/zevenet.com.gpg.key | apt-key add -
# echo deb http://repo.zevenet.com/ce/v5/ buster main > /etc/apt/sources.list.d/zevenet.list
# apt update --no-list-cleanup -o Dir::Etc::sourceparts="-" -o Dir::Etc::sourcelist="sources.list.d/zevenet.list"
# apt upgrade --with-new-pkgs  -o Dir::Etc::sourceparts="-" -o Dir::Etc::sourcelist="sources.list.d/zevenet.list"
# apt install zevenet
# apt install zevenet-gui-core

Regarding the installation of zcli we have not been able to reproduce the issue. Note to the ZEVENET load balancer uses some packages from Debian public repositories, please ensure that additional Debian repositories are configured.

For more information about How to configure APT repository for ZEVENET Community Edition, refer to this article:
https://www.zevenet.com/knowledge-base/howtos/configure-apt-repository-zevenet-community-edition/

Soon we will start working on the new Debian Bullseye distribution.

For further help, please let us know.
Kind regards.

**Comment by dboc** [comment]
Hi,

Thanks. It works!

**Comment by adanmarin-zevenet** [comment]
Great, thanks for the confirmation, we will proceed to close this ticket.

If further help is needed, do not hesitate to contact us, we are glad to assist you.

Best regards.
