### ISSUE TITLE
4.0 Admin UI allows unauthenticated access

### ISSUE THREAD

**Issue by mainframe** [zevenet/zlb#12]
It seems that ZLB 4.0 admin UI does not do http auth anymore - so anyone can access it.

**Comment by mainframe** [comment]
Auth is left disabled in cherokee config file:

cat /usr/local/zenloadbalancer/app/cherokee/etc/cherokee/cherokee.conf | grep '#vserver!1!rule!500!auth'
#vserver!1!rule!500!auth = htpasswd
#vserver!1!rule!500!auth!methods = basic
#vserver!1!rule!500!auth!passwdfile = /usr/local/zenloadbalancer/app/cherokee/etc/cherokee/.htpasswd
#vserver!1!rule!500!auth!realm = Zen Load Balancer GUI

Workaround:
* uncomment these lines
* reboot (or HUP cherokee)

**Comment by nevola** [comment]
Hi Andres! I've just committed bbd995470050211a21d8509ec7b9d73d89eadd47 with the fix, please confirm if it's solved in order to close the issue. Thank you for your report.

**Comment by mainframe** [comment]
Seems ok to me!
