### ISSUE TITLE
Zevenet Origin IP

### ISSUE THREAD

**Issue by patebert** [zevenet/zlb#127]
Hello, 
we have Zevenet Loadbalancer installed for some time and it works great.
Now we have switched on a monitor on our Active Directorys, which logs the failed logins and had to realise that it unfortunately always uses the IP of the Zevent as the source IP.
I know that this can be bypass with HTTP/S by using the header X-Forwarded-For. However, we also have services such as Radius and LDAP running via the Loadbalancer.
We are aware that you can change the NAT type to DSR.
However, this also means that we would have to open our firewall, as the response from the backend (Active Directory) goes directly back to the client.
Does anyone here have another solution for finding out what the original IP of the sender is?

Thank you in advance and best regards,
Patrick

**Comment by nevola** [comment]
Hi @patebert

To do that, I recommend to set L4 DNAT and the only requirement is to configure the load balancer as a default gateway in your backends.

Refer to the DNAT approach in this article:
https://www.relianoid.com/resources/knowledge-base/lslb/enterprise-edition-v6-2-administration-guide-lslb-farms-update-l4xnat-profile/

Hope this helps.

**Comment by patebert** [comment]
Hello nevola,

thank you for this idea.
We will try it in our test environment.

Best regards,

**Comment by nevola** [comment]
Welcome!
I'll close this issue.

Kind Regards.

**Comment by patebert** [comment]
One question @nevola, 
we had tested this with a static route and it showed me the original IP.
However, we now had the question of how it looks in an Active Directory environment, which of course not only LDAP and Radius offers, but also Kerberos makes, where again the Zevenet has no interface for each service.
If the default gateway is now on the load balancer on the AD, then the requests from Kerberos and co. would run into the void Or the packets are dropped, right? 

Best Regards

**Comment by emilio-campos-skudonet** [comment]
Hi @patebert this question should be replied knowing better the network architecture, could you share some example?

If Kereberos Server tries to reach AD backend directly (no usage of LB) then the kerbero's gateway should know that the AD backend is reachable know by a new gateway (The LB). 

At the moment you decide to use the Load Balancer as Gateway the other gateways has to know that if a backend behind the LB using the LB as gw need to be reached then the packet need to be sent to the Lb working as gateway.

I hope it helps Regards.

**Comment by nevola** [comment]
> One question @nevola, we had tested this with a static route and it showed me the original IP. However, we now had the question of how it looks in an Active Directory environment, which of course not only LDAP and Radius offers, but also Kerberos makes, where again the Zevenet has no interface for each service. If the default gateway is now on the load balancer on the AD, then the requests from Kerberos and co. would run into the void Or the packets are dropped, right?
> 
> Best Regards

Hi @patebert! you can use static routes in the AD backends to avoid to go through the load balancer when the connection is directly steered to the Kerberos, LDAP or Radius.

Kind Regards.
