### ISSUE TITLE
Outlook can't connect to Exchange 

### ISSUE THREAD

**Issue by danielbaessler** [zevenet/zlb#130]
Hello i have thé Problem that my Outlook can't connect to my Exchange Cluster.
OWA is working

**Comment by nevola** [comment]
Hi Daniel, which configuration are you using for such service?

Cheers.

**Comment by danielbaessler** [comment]
I using the the MAPI over HTTP and in the balancer i use the HTTP Listner

**Comment by nevola** [comment]
Hi @danielbaessler try to use l4xnat in NAT mode.

Kind Regards.

**Comment by danielbaessler** [comment]
Thanks its working fine
