### ISSUE TITLE
Change Admin Password Error

### ISSUE THREAD

**Issue by bbarendt** [zevenet/zlb#18]
After installing Zevenet 4.0.1 Community Edition I am unable to reset the admin password through the UI.  I get an error that the current password I am providing is invalid.

**Comment by bbarendt** [comment]
FYI, I think this has to do with htpasswd.  When I try to run htpasswd from command line I get the error "cannot execute binary file: exec format error"

**Comment by emiliocampos-zevenet** [comment]
Seems like there is an issue with the variable with the http users and password for Basic Authentication, the issue has been solved in the commit ca02c0e
