### ISSUE TITLE
Cookie Persistence Broken

### ISSUE THREAD

**Issue by prof79** [zevenet/zlb#20]
Hello there,

we would need the cookie persistence feature for an MS RDWeb farm (terminal server web pages).

However, cookie persistence is still broken in ZEVENET CE 4.01 - also had the problem in ZLB 3.10.1 and the version before.

How to reproduce:

* Edit the farm.
* Go to the service section.
* Under "Persistence session", select "COOKIE ...".
* Click "Modify".
* Under "Persistence session identifier. *a cookie name, a header name or url value name" enter your cookie name in the text box.
* Click "Modify".
* Now the "Persistence session identifier ..." text box will be empty and restarting the farm wouldn't work either due to "ERROR! Farm testfarm can't be stopped, check the logs and modify the configuration."
* You can try entering a cookie name and click "Modify" as often as you like, but the persistence cookie won't be persisted ;-)
* Have to switch back to "IP: ..." to get it working again.

This is of high impact in more complex farm scenarios. Please fix or if you don't want this to be a community feature state it clearly and remove the option.

Thank you!

**Comment by emiliocampos-zevenet** [comment]
Dear prof79, I am not able to reproduce the issue, I created a given service with name "test" and configured here a cookie persistence with cookie name "JSESSIONID",the restart worked as expected.

Please could you let us know the following names: 
Farm Name you created
Service name you created
Cookie name you configured. 

Maybe a regexp is not properly created and it is failing with a given string that you are using.

**Comment by prof79** [comment]
Dear emiliocampos-zevenet,

I've tried two farms, the real one and a test one:

Farm name: `riga-https`
Service name: `RDWeb`
Cookie name: `TSWAuthClientSideCookie`

Farm name: `testfarm`
Service name: `testpage`
Cookie name: `TEST`

Now I think I've found a path to the solution of this riddle: You gave me a good hint. When I delete the service and recreate it, session cookie starts working from the get-go (default value filled-in, too).

I'm under the impression that there is something wrong in the configuration files which I restored from previous versions going away when re-creating the service. Need to investigate more.

**Comment by prof79** [comment]
Couldn't figure out the textual differences in the old config file causing this but re-creating the farm from scratch worked!

(Note to others looking for RDWeb under Server 2008 R2: Use `TSWAAuthHttpOnlyCookie` as a cookie name, seems to work like a charm so far not seeing the dreaded yellow stacktrace page again)

Do you want to diagnose further or should I close the ticket? Btw I noticed - I'm not even allowed to add a farm with a dash in the name in 4.x anymore - maybe this is where the problem started some two or three versions ago.

**Comment by emiliocampos-zevenet** [comment]
Hi think the issue happens if before to configure persistence cookie you have configured ip persistence. So I will check more in order to find the issue.

Thanks for your latest reports it helps

**Comment by fredyluque-zevenet** [comment]
Dear prof79,
We have taken up the matter again just to test if the problem persist. We have not been able to reproduce it. The farm´s persistence session identifier can be modified as it should, and it restart without problem.
Thanks for your interest anyway.
