### ISSUE TITLE
apt Path for 4.x

### ISSUE THREAD

**Issue by prof79** [zevenet/zlb#21]
Hello,

the (old) [community installation guide](https://www.zevenet.com/knowledge-base/community-edition/community-edition-v3-05-administration-guide/community-edition-v3-05-installation-guide/) mentions this apt repository:

* For v3 version: `deb http://zenloadbalancer.sourceforge.net/apt/x86 v3/`

Could anyone add v4 info on that page? Would an URL like the following be correct?

`deb http://zevenet.sourceforge.net/apt/x86 v4/`

? (just a guess)

Thanks!

**Comment by emiliocampos-zevenet** [comment]
Hi, there is a dedicated mini how-to for this available from Zevenet KB. 

https://www.zevenet.com/knowledge-base/howtos/configure-apt-repository-zevenet-community-edition/

Please check and let us know for closing this ticket. 

Regards

**Comment by prof79** [comment]
Thanks a lot! Exactly what I needed.

Regards
