### ISSUE TITLE
Version number in 'about' menu

### ISSUE THREAD

**Issue by Benoire** [zevenet/zlb#23]
Hello

I've noticed that only the title bar shows a version number, and I'm not sure whether its actually correct.  It would be beneficial for users of the community version to at least add a new section under the about menu which tells you what version your running... Even better would be if it could indicate that an update has been posted so that we can update the program.

**Comment by fredyluque-zevenet** [comment]
Hello Benoire,

Thanks for your proposal. 
It has been already added!
