### ISSUE TITLE
Version number not right after updating to v4.0.4

### ISSUE THREAD

**Issue by thiesuh** [zevenet/zlb#24]
Yesterday we did a update to v4.0.4. Before we updated the load balancer we put them in maintenance mode. After the update we saw that the version number was correct
![showing v4 0 4](https://user-images.githubusercontent.com/28976565/27422351-1c5f1574-572e-11e7-9a23-95c0265df270.PNG)
After updating the second load balancer and do a test fail over all of a sudden the version number changed to v4.0.1 on both load balancers. I believe it happend after we did a test fail over but i am not sure.
![showing v4 0 1](https://user-images.githubusercontent.com/28976565/27422485-a0292f98-572e-11e7-9205-67be0839f0fd.PNG)

Hope you can take a look at it.

Dirk

**Comment by nevola** [comment]
Hi! How have you updated the new version?
There was any error during the update?

If you've a cluster please ensure to disable it before the update, or
disable the replication service.

Regards!

**Comment by thiesuh** [comment]
The load balancer were in a cluster while updating, i think that was the issue. There where no errors while updating

**Comment by nevola** [comment]
Yes, you've to disable the cluster, then try to update again and finally rebuild the cluster.
If you've further doubts please ask in the official mailing list.
