### ISSUE TITLE
Password change with sync dont work

### ISSUE THREAD

**Issue by HALi1337** [zevenet/zlb#25]
Hello I install a fresh Zevenet installation. I change the admin password "admin" to an new password with root sync. After this change I cant login into the web admin interface. The root login on the console works fine.

How can I change the web admin password via ssh? passwd admin dont work because no user existing.

**Comment by emiliocampos-zevenet** [comment]
Hellow, what version are you working with? it should be solved in zevenet ce 4.0.5,  please confirm your zevenet load balancer is updated

**Comment by HALi1337** [comment]
I downloaded the ISO from https://sourceforge.net/projects/zevenet/

Version 4.0.4 :-/

**Comment by emiliocampos-zevenet** [comment]
Issue solved in zevenet 5, admin user is not used any more. use root instead it validates against the system
