### ISSUE TITLE
Multi-Domain Wildcard Certificates

### ISSUE THREAD

**Issue by bbarendt** [zevenet/zlb#26]
we currently have the enterprise edition running in our production and qa environments, but I am installing the community edition in my personal test lab environment, when I attempt to use our Multi-Domain Wildcard certificate, the farm that has this cert attached will not start - it will start if I use the built-in zevenet cert - the cert I am trying to use is the same one we have in production.

**Comment by emiliocampos-zevenet** [comment]
Good morning bbarendt, https profiles in community edition use pound package from debian repo, but  enterprise edition uses pound with some modifications we have developed, all our code is released in the following git: 

https://github.com/zevenet/pound

You could try to download the source code, compile and change the binary pound in the community version, the feature related with the Multi-Domain wildcard should work. 

Thanks!

**Comment by frayber** [comment]
I'm using community edition 4.0.5 with wildcard caertificate without problems

**Comment by wobstyr** [comment]
I having the same issue with zevenet 5.1, it doesn't matter what i do, the cert fails, whats interesting if i take the working pem cert from my other zenlb 3.04 it works perfectly.

**Comment by emiliocampos-zevenet** [comment]
Wildcard certificate is not supported in pound by default, you have to use
the available pound fork in our public github

HTTPS://www.github.com/Zevenet/pound

**Comment by emiliocampos-zevenet** [comment]
Not supported in 5.0.1 you have to use our forked pound instead


Compile and change the binary

**Comment by wobstyr** [comment]
Thank you, probably a stupid question, but how do you install it on to zevenet 5.01? 
i ran  ./configure then make and i got an error. 

config.c: In function ‘parse_service’:
config.c:723:25: warning: implicit declaration of function ‘LHM_lh_new’ [-Wimplicit-function-declaration]
     if((res->sessions = LHM_lh_new(TABNODE, t)) == NULL)
                         ^~~~~~~~~~
config.c:723:36: error: expected expression before ‘TABNODE’
     if((res->sessions = LHM_lh_new(TABNODE, t)) == NULL)
                                    ^~~~~~~
<builtin>: recipe for target 'config.o' failed
make: *** [config.o] Error 1

**Comment by emiliocampos-zevenet** [comment]
The compilation error is related with the libssl1.0-dev library, it is needed for this pound version, surely you installed libssl-dev (version 1.1, which isn't supported in pound) 

You have to install libssl1.0-dev library and compile again.

As soon the new pound and poundssl is created you have to substitute them in the following path:

[backup] root@zce52cl12:~# which pound
/usr/sbin/pound

[backup] root@zce52cl12:~# which poundctl
/usr/sbin/poundctl

**Comment by wobstyr** [comment]
worked like a charm, thank you

**Comment by emiliocampos-zevenet** [comment]
So, we will proceed to close the ticket after all. 
Thanks!
