### ISSUE TITLE
clustering on Citrix XEN server

### ISSUE THREAD

**Issue by wjterveld** [zevenet/zlb#27]
Hello,

When installing a zevenet cluster on Citrix XEN server there is a problem when the LB'ers are on different XEN hosts. They lose communication apparently Zevenet and XEN use the same port/protocol.

Will there be a fix for this?

**Comment by emiliocampos-zevenet** [comment]
Zevenet Community Edition uses UCARP binary, it implements vrrp protocol and sends traffic to multicast, so you should confirm your xenservers and virtual / physical switches support multicast too. 

Regards
