### ISSUE TITLE
debian stretch support

### ISSUE THREAD

**Issue by Mikki-black** [zevenet/zlb#29]
Are there any plans to make this available for debian stretch?

**Comment by emiliocampos-zevenet** [comment]
Yes, we are currently working in next Zevenet CE 5.0, it will be included in a debian stretch base.

We hope to release this version in a month, anyway we will update our timeline asap: https://www.zevenet.com/support/resources/timeline/

where you will see new features.

**Comment by Mikki-black** [comment]
Thanks for the update, looking forward to it :+1:

**Comment by emiliocampos-zevenet** [comment]
The version was released, debian stretch has been used for this new Version Zevenet 5.

**Comment by Mikki-black** [comment]
Thank you!
