### ISSUE TITLE
CE 5.0 installation hangs on Hyper-V

### ISSUE THREAD

**Issue by ojarmes** [zevenet/zlb#30]
On my Hyper-V hosts the installation hangs after 33%, "Partitions formatting".

Hyper-V 2012 an 2016, Gen1 vm with 1024 MB fixed ram and 10 GB harddisk. Any hints?

CE 4.0.5 works fine for me.

**Comment by ftamayo1** [comment]
My installation also hangs in the same spot as reported by ojames. Hyper-V 4GB of RAM and 40GB harddrive

**Comment by emiliocampos-zevenet** [comment]
Hi @ftamayo1 this is a known issue in zevenet 5.0 community edition, based in a bug in a HyperV kernel module, we need to create the Operating system again so this task is taking time.

**Comment by emiliocampos-zevenet** [comment]
It will be solved in a new Zevenet installer, the current installer for zevenet 5.0.1 doesn't support hyperv
