### ISSUE TITLE
CE 5.0 misunderstands /etc/resolv.conf

### ISSUE THREAD

**Issue by wusel42** [zevenet/zlb#32]
With ...

```
root@lb01:~# cat /etc/resolv.conf 
search 4830.org
nameserver 192.251.226.10
nameserver 1.1.1.1
nameserver 9.9.9.9
```
the UI states that first DNS server would be "4830.org", second DNS server "192.251.226.10". Fixing this in the UI yields:

```
root@lb01:~# cat /etc/resolv.conf 
nameserver 192.251.226.10
nameserver 1.1.1.1
nameserver 1.1.1.1
nameserver 9.9.9.9
```
=> parser needs to check keyword, not rely on any second argument being a name server address.

**Comment by emiliocampos-zevenet** [comment]
Good morning, yes it is true, parser is not managing any value different to "nameserver" after all. 

We will solve it.

**Comment by cano-devel** [comment]
This is solved
