### ISSUE TITLE
zlb-debian-installer.sh fails with error

### ISSUE THREAD

**Issue by ZenMonk** [zevenet/zlb#33]
Linux debian-s-2vcpu-2gb-nyc1-01 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

./zlb-debian-installer.sh fails with the following error:

* Fetching Zevenet gpg key: OK
* Updating packages database
Ign:1 http://mirrors.digitalocean.com/debian stretch InRelease
Hit:2 http://security.debian.org stretch/updates InRelease
Get:3 http://mirrors.digitalocean.com/debian stretch-updates InRelease [91.0 kB]
Hit:4 http://mirrors.digitalocean.com/debian stretch Release
Get:5 http://repo.zevenet.com/ce/v5 stretch InRelease [1,749 B]
Reading package lists... Done
E: Release file for http://repo.zevenet.com/ce/v5/dists/stretch/InRelease is expired (invalid since 1d 10h 49min 21s). Updates for this repository will not be applied.

**Comment by ZenMonk** [comment]
To work around, I set the system date to 5/22 and reran the installer with the following result:

* Fetching Zevenet gpg key: OK
* Updating packages database
Ign:1 http://mirrors.digitalocean.com/debian stretch InRelease
Get:2 http://mirrors.digitalocean.com/debian stretch-updates InRelease [91.0 kB]
Get:3 http://repo.zevenet.com/ce/v5 stretch InRelease [1,749 B]
Hit:4 http://security.debian.org stretch/updates InRelease
Hit:5 http://mirrors.digitalocean.com/debian stretch Release
Fetched 92.8 kB in 0s (141 kB/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-amd64/Packages' as repository 'http://repo.zevenet.com/ce/v5 stretch InRelease' doesn't support architecture 'amd64'
* Installing dependencies
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package cherokee is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'cherokee' has no installation candidate
E: Unable to locate package zevenet-gui-ce

**Comment by ZenMonk** [comment]
I'm building cherokee webserver, the instructions may need to be updated with the following:
**apt-get install libtool-bin**

**Comment by ZenMonk** [comment]
In addition, with a fresh Debian install, I had to do the following:
**apt-get install gettext**
**apt-get install make**

**Comment by ZenMonk** [comment]
OK, I'm stuck.  For cherokee webserver, **make** and **make install** were successful.  So, without any other direction, I went back to ZLB and reran **"./zlb-debian-installer.sh"**.  However, this fails with the following:

* Fetching Zevenet gpg key: OK
* Updating packages database
Hit:1 http://security.debian.org stretch/updates InRelease
Hit:2 http://repo.zevenet.com/ce/v5 stretch InRelease
Ign:3 http://lon1.mirrors.digitalocean.com/debian stretch InRelease
Hit:4 http://lon1.mirrors.digitalocean.com/debian stretch-updates InRelease
Hit:5 http://lon1.mirrors.digitalocean.com/debian stretch Release
Reading package lists... Done
**N: Skipping acquire of configured file 'main/binary-amd64/Packages' as repository 'http://repo.zevenet.com/ce/v5 stretch InRelease' doesn't support architecture 'amd64'**
* Installing dependencies
Reading package lists... Done
Building dependency tree
Reading state information... Done
**Package cherokee is not available, but is referred to by another package.**
**This may mean that the package is missing, has been obsoleted, or
is only available from another source**

**E: Package 'cherokee' has no installation candidate
E: Unable to locate package zevenet-gui-ce**

**Comment by MBcom** [comment]
Any update on this?
We have currently the same installation problems...

**Comment by emiliocampos-zevenet** [comment]
Stretch repo only for 32 bits, the issue with the inRelease data has been already solved. 


root@zevenetce5:~# apt-get update
Obj:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://ftp.es.debian.org/debian stretch InRelease                                
Obj:3 http://ftp.es.debian.org/debian stretch-updates InRelease                        
Obj:4 http://ftp.es.debian.org/debian stretch Release                                  
Obj:6 http://repo.zevenet.com/ce/v5 stretch InRelease                                  
Leyendo lista de paquetes... Done
root@zevenetce5:~# uname -a
Linux zevenetce5 4.9.0-4-686-pae #1 SMP Debian 4.9.65-3 (2017-12-03) i686 GNU/Linux

**Comment by muzzol** [comment]
is there any way to install it on 64b machine with this script?

**Comment by emiliocampos-zevenet** [comment]
Not actually, it is in our TODO list, pending to be done.

**Comment by Aleksey-Maksimov** [comment]
Hello muzzol
If you are satisfied with the old version of ZLB, then you can use our fork: https://github.com/vlet/zlb
At us this version works till today.
links to deb packages and a description of the deployment procedure can be found here (use the Google translator) : https://blog.it-kb.ru/2016/12/21/high-availability-nlb-cluster-l4xnat-and-http-on-virtual-zlb-zevenet-load-balancer-community-edition-3-10-1-on-64-bit-debian-linux-8-6-jessie-on-ovirt-4-0-vm-with-mac-spoofing-with-iptables-rules/

**Comment by cano-devel** [comment]
We aren't giving support to the zlb-debian-installer.sh. The Zevenet installation method is through the apt repository. So we are going to close the issue, it hasn't sense in new versions.
