### ISSUE TITLE
CE 5.0 farm editor truncates server list

### ISSUE THREAD

**Issue by balance819** [zevenet/zlb#34]
After creating an lx4nat farm and populating it with 10 servers (ID 0-9), any additional new servers will not appear in the UI's list after being saved. Testing and examining the configuration file for the farm reveals the servers are being added and seem to function normally. so I suspect the bug is isolated to the UI.

**Comment by crissty** [comment]
Dear @balance819 , thanks for this report. 
Effectively, there was an issue in the backends table that it did not show the backends with ID higher than 9.
This has been solved in the new version 1.0.1 of **zevenet-gui-ce** package that it has been released today.

You can update the package as follow:
`apt-get update`
`apt-get install zevenet-gui-ce`


Regards.

**Comment by balance819** [comment]
Updated and it is working perfectly. Thank you for the quick fix!
