### ISSUE TITLE
Multi-Domain Issues

### ISSUE THREAD

**Issue by wobstyr** [zevenet/zlb#35]
I have the latest and greatest version of zevenet 5.01 I have upgraded pound to the latest version. however it doesn't matter what i do, i cannot get it to accept a valid certificate. at a loss what to do next.

**Comment by emiliocampos-zevenet** [comment]
Hi @wobstyr , zevenet accepts pem certificates without problem, here a how-to:
https://www.zevenet.com/knowledge-base/howtos/create-certificates-pem-format/

Zevenet 5.0.1 uses pound binary for ssl offloading, the pound binary in debian repository doesn't support wildcard certificates so you have to use the forked pound in our git https://www.github.com/zevenet/pound for supporting wildcard.

Thanks!

**Comment by emiliocampos-zevenet** [comment]
Duplicated with ticket #26
