### ISSUE TITLE
Adding Ports to a Farm

### ISSUE THREAD

**Issue by neilforg** [zevenet/zlb#37]
Hello,

I am wondering if it is possible to assign a collective list of ports to a backend.  We have a render farm application where a job sends and needs to return a status bar to the client via the higher TCP port range 50000 - 61000, and we're wondering if this may be a limitation for us as only one port can be listed at a time.

Thank you.

**Comment by emiliocampos-zevenet** [comment]
it can be done with l4xnat farm and add to the vip the port range as follows:
50000:61000

the character : indicates range.

On the other and in the backend table don't configure any value in column port.
