### ISSUE TITLE
Zevenet-Ce-V5.0 Cut mode is not disconnecting the Web Url

### ISSUE THREAD

**Issue by venbay** [zevenet/zlb#38]
Zevenet-ce 5.0 Load balancer Created HTTP farm and tries using using CUT mode but it is not disconnecting the Web URL unless i reboot the Farm restart daemon. Please advise.

**Comment by cano-devel** [comment]
Hello @venbay, 
I tested the cut connections feature and it is working properly in the last version 5.9.2. 
If you have this problem in the 5.9.2 version, please, attach more information in order to try to reproduce it in the lab.
