### ISSUE TITLE
Farm with Hyphen in Name Breaks When Persistence Enabled

### ISSUE THREAD

**Issue by adamnoyes** [zevenet/zlb#40]
When configuring an L4 NAT farm with a hypen in it's name (ex. 389-LDAP), everything works as expected as long as persistence isn't enabled.  As soon as persistence is enabled, the farm refuses to start and the UI shows many fields as being either unselected (drop-downs) or with a value of -1.  An example of the JSON data that is exchanged in this case:

PUT https://<ip>/zapi/v3.1/zapi.cgi/farms/389-LDAP
Params:
persistence: ip

Response:
{
   "description" : "Modify L4xNAT farm '389-LDAP'",
   "params" : {
      "persistence" : "ip"
   }
}

GET https://<ip>/zapi/v3.1/zapi.cgi/farms/389-LDAP
Response:
{
   "backends" : [],
   "description" : "List farm 389-LDAP",
   "params" : {
      "algorithm" : -1,
      "fgenabled" : "false",
      "fglog" : "false",
      "fgscript" : "",
      "fgtimecheck" : 5,
      "listener" : "l4xnat",
      "nattype" : -1,
      "persistence" : "-1",
      "protocol" : -1,
      "status" : "critical",
      "ttl" : 0,
      "vip" : -1,
      "vport" : "-1"
   }
}

**Comment by cano-devel** [comment]
The last Zevenet version hasn't got l4 persistence. So, this issue is not been happening at the moment.
