### ISSUE TITLE
Issue when changing Farm SSL certificate from web interface

### ISSUE THREAD

**Issue by Dx64gx** [zevenet/zlb#44]
I've noticed an issue occurring in Zevenet CE 5.0.1 when trying to change an SSL certificate for a HTTP farm. The interface give an error of "An error has occurred on the server, try again later". When I look at the Cherokee error log I see:

Undefined subroutine &main::getFarmCertificate called at /usr/share/perl5/Zevenet/API31/Certificate/Farm.pm line 63.
Compilation failed in require at /usr/local/zevenet/www/zapi/v3.1/zapi.cgi line 94.

I am able to change the certificate without issue in the farm config file.

**Comment by BestBackwards** [comment]
Just to add, this is DEFINITELY an issue.
Really wish I had seen this 5 hours ago. I've been going nuts recreating certificates!

**Comment by cano-devel** [comment]
Hello,

Thanks for the report.
We have released a new minor version 5.0.2  with this bugfix and others.

Please upgrade your Zevenet package:

apt-get update
apt-get install zevenet

Have a good day.

**Comment by Dx64gx** [comment]
The issue has definitely been resolved. Thanks!
