### ISSUE TITLE
HTTP/2 Support

### ISSUE THREAD

**Issue by georgeemr** [zevenet/zlb#45]
I see that in the 2018 roadmap HTTP/2 was going to be supported. I was checking the timeline but I don't see any HTTP/2 support added. Just want it to know if the support is going to be available in the January update?

**Comment by emiliocampos-zevenet** [comment]
HTTP2 has been re-scheduled for the next year, we will try to release this feature the 2Q, but not confirmed yet. 

Thanks!

**Comment by georgeemr** [comment]
Thanks for the answer!

**Comment by danbeck** [comment]
Is there some new information about when HTTP/2 going to be supported?

**Comment by nevola** [comment]
Hi! Hope to have it for October 2022 as a beta release.
Kind Regards.

**Comment by danbeck** [comment]
Is the work on HTTP/2 going on?

Using HTTP/1 really hurts website performance when delivering many images. Could you reopen the issue?
