### ISSUE TITLE
Cluster on 5.9

### ISSUE THREAD

**Issue by georgeemr** [zevenet/zlb#46]
Hi, thanks a lot for the last update! It's what I have been waiting.

I was going to install the Zevenet Load Balancer Community Edition Cluster Service but on apt-cache search I dont get any result.

![image](https://user-images.githubusercontent.com/3822009/51270400-6740ec00-198a-11e9-8db6-bb9ccdde1f0a.png)

Is the cluster service be available in this version?
Thanks in advance!

**Comment by emiliocampos-zevenet** [comment]
apt-get update

apt-cache search zevenet-ce-cluster

This package is available in stretch and buster as well.

El mié., 16 ene. 2019 a las 19:30, georgeemr
(<notifications@github.com>) escribió:
>
> Hi, thanks a lot for the last update! It's what I have been waiting.
>
> I was going to install the Zevenet Load Balancer Community Edition Cluster Service but on apt-cache search I dont get any result.
>
> Is the cluster service be available in this version?
> Thanks in advance!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

Emilio Campos

Development and Support Department

www.zevenet.com




DISCLAIMER: This message contains confidential information and is
intended only for the individual named. If you are not the named
addressee please notify the sender immediately by email if you have
received it by mistake and delete it from your system, you should not
disseminate, distribute or copy this email in whole or in part.

**Comment by georgeemr** [comment]
Thanks Emilio!

**Comment by georgeemr** [comment]
Can i have more than two Zevenet servers responding to the cluster?
For example 3-4 servers.

I see on the example in the documentation that there's the master and the backup. Can I have two backups? Or what could be the best scenario when you have more than two Zevenet servers.

Thanks in advance.

`#interface used for the cluster where is configured local_ip and remote_ip
$interface="eth0";

#local IP to be monitored, i e 192.168.0.101
$local_ip="192.168.101.242";

#remote IP to be monitored, i e 192.168.0.102
$remote_ip="192.168.101.243";

#used password for vrrp protocol communication
$password="secret";

#unique value for vrrp cluster in the network
$cluster_id="1";

#used virtual IP in the cluster, this ip will run always in the master node
$cluster_ip="192.168.101.244";

$exclude="--exclude if_eth0_conf";`

**Comment by emiliocampos-zevenet** [comment]
No just two servers

**Comment by georgeemr** [comment]
Thanks!
