### ISSUE TITLE
Can't set  Port  in l4xnat farm probile

### ISSUE THREAD

**Issue by ismailyenigul** [zevenet/zlb#50]
I am using version 5.9, I added an l4xnat farm and tried to add backend for this service.
But there is only ID,IP, Weight and priority.
How can I specify a port on the backend?  The backend port is different than zlb listener port.
There was a Port option for the l4xnat in version 5.0.

**Comment by emiliocampos-zevenet** [comment]
We are working on this, internally still in development, we hope to release a new version with this and other features at the end of May.

**Comment by ismailyenigul** [comment]
ah ok.
So I have to switch to 5.0 to have this feature right?

**Comment by emiliocampos-zevenet** [comment]
Yes, it is an option, or keep going with this version with another Farm in the needed port. But if for you it is a must, then you have to keep the previous version.

**Comment by ismailyenigul** [comment]
ok thanks
