### ISSUE TITLE
 X-Forwarded-Proto header for HTTPS farm

### ISSUE THREAD

**Issue by ismailyenigul** [zevenet/zlb#52]
Hello,

Does ZLB v5.0 add  X-Forwarded-Proto header for https listener while sending traffic to HTTP backend?

Thanks

**Comment by nevola** [comment]
In the Community Edition, you've to add it in the configuration file manually. In the Enterprise Edition, it could be done through web GUI.

**Comment by ismailyenigul** [comment]
can you please tell me  which configuration file is this for Community edition?

Thanks

**Comment by nevola** [comment]
Please take a look to this example:
https://www.zivtech.com/sites/default/files/etc.pound_.pound_.cfg_.txt

In addition, please use the official distribution list for further support. This section is only used for bugs.
[https://www.zevenet.com/support/resources/#distributionlist](https://www.zevenet.com/support/resources/#distributionlist)

Thanks!
