### ISSUE TITLE
Can't change LSLB Farms Profile type

### ISSUE THREAD

**Issue by andylin-1117** [zevenet/zlb#53]
I've noticed an issue occurring in Zevenet CE 5.0 when trying to change the Listener from HTTP to HTTPS for a HTTP farm. The interface give an error of "An error has occurred on the server, try again later". When I look at the Cherokee-error log I see:

Undefined subroutine &main::getFarmCertificate called at /usr/share/perl5/Zevenet/API31/Farm/Put/HTTP.pm line 608.
Compilation failed in require at /usr/local/zevenet/www/zapi/v3.1/zapi.cgi line 94.
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
Then after I tried to upgrade Zevenet CE to version 5.0.2, the problem was the same. I see the Cherokee-error log:

Undefined subroutine &main::getFarmCertificate called at /usr/share/perl5/Zevenet/API31/Farm/Put/HTTP.pm line 589.
Compilation failed in require at /usr/local/zevenet/www/zapi/v3.1/zapi.cgi line 94.

How should this problem be solved? Thanks a lot.

**Comment by cano-devel** [comment]
Hello @andylin-1117, this bug is patched in the last Zevenet version 5.10.1.
Thanks for your report
