### ISSUE TITLE
I want to use  Zevenet CE  5.0

### ISSUE THREAD

**Issue by hakanbayraktar** [zevenet/zlb#56]
Hi,  I want to use  Zevenet CE  5.0.
But I couldn't find Zevenet CE v5.0 iso. Where can I download it?

**Comment by cano-devel** [comment]
Hi @hakanbayraktar,
Unfortunately, we have not available any older ISO. When we release a new ISO we don't continue updating the last ones. 
If the last ISO is not useful for you, you can get the code from the branch v5 (in this repo) and deploy it in a Debian Stretch. But notice that we are not fixing bugs or giving support in older versions.
Have a good day.
