### ISSUE TITLE
Zevenet Cluster IP Issue

### ISSUE THREAD

**Issue by toromanoski** [zevenet/zlb#58]
Hi, 

I'm trying to setup master - backup cluster configuration on zevenet-ce-cluster. 

Cluster is working fine while i have just one cluster IP, but when i add secondary cluster IP, when i'm trying to test and suspend master node, i'm loosing ping to the secondary cluster IP. 

Can someone help me? 

Thanks, 
Bojan

**Comment by emiliocampos-zevenet** [comment]
Refer to the emailing list , this is for reporting bugs and it seems a
misconfiguration issue.
