### ISSUE TITLE
Zevenet Version: 5.10.1 http farm url pattern error 503

### ISSUE THREAD

**Issue by pnagibin** [zevenet/zlb#60]
Hello

I 've created https farm and it works fine without url pattern

When i add url pattern i get error 503

I have exactly the same farm on Zevenet Version: 5.9.3 with url pattern ant it works

![image](https://user-images.githubusercontent.com/57600427/68549422-bcae2400-0408-11ea-8c63-e5abf82600e7.png)

![image](https://user-images.githubusercontent.com/57600427/68549574-9db09180-040a-11ea-8b15-1c32ab0c9b7e.png)

[supportsave_krv-lb01_20191110_2147.tar.gz](https://github.com/zevenet/zlb/files/3828885/supportsave_krv-lb01_20191110_2147.tar.gz)

**Comment by adanmarin-zevenet** [comment]
Good day,

We have tested in the latest version and the issue seems to be solved. Please, update with the following command:

apt-get update && apt-get install zproxy

Check that you don't have any redirect in the backend.

**Comment by adanmarin-zevenet** [comment]
Good day,
did you have the chance to update and check that the issue has been solved?

**Comment by adanmarin-zevenet** [comment]
Good day,
We will proceed to close this ticket after a while without updated information.
