### ISSUE TITLE
how to check if current node is master/ backup/maintenance using command? 

### ISSUE THREAD

**Issue by roimekoi** [zevenet/zlb#64]
I setup a cluster, and found out that both virtual are up, this was not the case in older version of community version.

is there a command i can use to verify which node is currently the master ? 

thanks and regards

**Comment by emiliocampos-zevenet** [comment]
Good morning, cluster shows the status in the prompt, prompt reads from the file /etc/zevenet-ce-cluster.status

Also in the master node the process zeninotify is running, but this process is not running in backup node. 

Additionally if you capture traffic from one of the nodes with:

tcpdump -i any vrrp

You will see traffic from the master IP to multicast. 

Thanks!
