### ISSUE TITLE
Adding multiple backends concurrently fail

### ISSUE THREAD

**Issue by mathianasj** [zevenet/zlb#65]
If I try to create two backends at the same time against L4XNAT farm only one backend gets created.

**Comment by nevola** [comment]
Hi Mathias, please check the syslog file looking for any raised error. Thanks!

**Comment by adanmarin-zevenet** [comment]
We are not able to reproduce this.

Please, try to upgrade to the latest version and confirm if it fixes the problem.

**Comment by adanmarin-zevenet** [comment]
Good day,
We will proceed to close this ticket after a while without updated information.
