### ISSUE TITLE
Persistence Issue

### ISSUE THREAD

**Issue by wobstyr** [zevenet/zlb#66]
I am using latest version of zevenet 5.10.1, if i add cookie persistence i don't get session saving up at all. 
if i use ip persistence, i get session loss after 10sec. any ideas?

I am using cloudflare as well.

**Comment by abdessamad-zevenet** [comment]
Hi,

Could you make sure that you have the latest versions of zproxy package,
please execute; apt-get update && apt-get install zproxy.

if the issue persist, please provide information on how to reproduce the issue.

**Comment by cano-devel** [comment]
after a while without feedback about this issue, we suppose it is solved
Regards
