### ISSUE TITLE
Syslog UDP: no return packet fills up connections table

### ISSUE THREAD

**Issue by randyb77** [zevenet/zlb#7]
The syslog udp protocol is one-way (one direction and no returned packet required).  When a large number of syslog messages (representing a large number of sending hosts) are sent to the Zen it may respond to the sending host with an ICMP "udp port unreachable" message.  Apparently, under heavy syslog load the conntrack memory fills up while waiting for a response from the farm servers which will never come.  The conntack has to time out on the return packet which produces an overrun of memory.

Can something be implemented, maybe a configuration variable, to increase the conntrack memory for these circumstances?  Or maybe an option to ignore return UDP packets?

**Comment by fredyluque-zevenet** [comment]
Dear sandyb77,,
As you suggest, this can be achieve with some kernel tuning. We do not include such functionalities on Community Edition. We customize those kind of parameters on the Enterprise Edition. We encourage you to do it yourself. You can find further info here: https://wiki.khnet.info/index.php/Conntrack_tuning
