### ISSUE TITLE
Zevenet ISO boot after install fail

### ISSUE THREAD

**Issue by Crash0v3r1de** [zevenet/zlb#91]
I think this would be the place to post issues with the ISO but I could be wrong.

The Community Edition ISO install fine obviously but upon first boot it fails to load and busybox shell is the loaded environment. To replicate the issue just install the system using the ISO and you'll get the issue.

Here is a screenshot of the console output - http://prntscr.com/vou7f8

**Comment by adanmarin-zevenet** [comment]
Good day,

It is working as expected, we can confirm The ISO Community Edition 5.11 boots and installs properly (see attached screenshots)..

We would need a step-by-step procedure to be able to reproduce it.

If the virtual BIOS uses UEFI, please, disable it and enable legacy mode instead.

This is an available URL to download the ISO.
https://es.osdn.net/projects/zevenet/storage/zevenet-ce_v5.11-amd64-v1.iso

![zlb-5 11-capture3](https://user-images.githubusercontent.com/45848272/100329732-5756b200-2fce-11eb-99d7-eb822042cf6e.png)
![zlb-5 11-capture2](https://user-images.githubusercontent.com/45848272/100329735-57ef4880-2fce-11eb-809c-94b200e97074.png)
![zlb-5 11-capture1](https://user-images.githubusercontent.com/45848272/100329736-5887df00-2fce-11eb-97a2-2d51c23eb13e.png)

Regards.

**Comment by Crash0v3r1de** [comment]
Interesting I re downloaded the ISO for the 6th time since you posted your screenshots and it now works.
